import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
type D=Record<string,string|number|boolean|null|undefined>;
const required=['nom','prenom','telephone','email','ville_pays','carte_ae','autorisation_generale','china_to_hub','receive_hub','maritime_to_algeria','site_delivery','primary_hub','hubs','van_status','rotations_month','micro_now','micro_30','micro_90','finance_operation_eur','finance_month_eur','commit_18m','rate_kg_eur','rate_unit_eur','rate_m3_eur','pricing_rule_ack','consent'];
const clean=(v:unknown)=>String(v??'').trim();
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const ascii=(v:unknown)=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-').replace(/€/g,'EUR');
function ref(){const d=new Date();return `${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,'0')}${String(d.getUTCDate()).padStart(2,'0')}-${crypto.randomUUID().replace(/-/g,'').slice(0,8).toUpperCase()}`}
function wrap(t:string,max=58){const a:string[]=[];let l='';for(const w of t.split(/\s+/)){const n=l?`${l} ${w}`:w;if(n.length>max&&l){a.push(l);l=w}else l=n}if(l)a.push(l);return a}
async function pdf(data:D,id:string){
 const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);
 const ink=rgb(.09,.09,.08),gold=rgb(.70,.57,.34),gray=rgb(.40,.39,.36),line=rgb(.86,.84,.78),W=595.28,H=841.89,m=46;
 let page=doc.addPage([W,H]),y=H-46;
 const header=()=>{page.drawText('ELITE',{x:m,y,font:bold,size:24,color:ink});page.drawText('DOSSIER CANDIDAT - LOGISTIQUE MICRO-IMPORTATION',{x:m,y:y-25,font:bold,size:10,color:gold});page.drawText(`Reference : ${id}`,{x:W-m-180,y,font:bold,size:10,color:gray});y-=54;page.drawLine({start:{x:m,y},end:{x:W-m,y},thickness:1,color:line});y-=24};
 const newp=()=>{page=doc.addPage([W,H]);y=H-46;header()};
 const sec=(t:string)=>{if(y<130)newp();page.drawText(ascii(t),{x:m,y,font:bold,size:12,color:ink});y-=18};
 const row=(l:string,v:unknown)=>{const ls=wrap(ascii(v)||'-'),h=Math.max(26,ls.length*13+8);if(y-h<55)newp();page.drawText(ascii(l),{x:m,y,font:bold,size:8.5,color:gray});ls.forEach((s,i)=>page.drawText(s,{x:m+165,y:y-i*13,font,size:9.5,color:ink}));y-=h;page.drawLine({start:{x:m,y:y+6},end:{x:W-m,y:y+6},thickness:.5,color:line})};
 header();
 sec('1. Identite et conformite');row('Nom / Prenom',`${clean(data.nom)} ${clean(data.prenom)}`);row('Telephone',data.telephone);row('Email',data.email);row('Ville / pays',data.ville_pays);row('Societe / reseau',data.societe);row('Carte auto-entrepreneur',data.carte_ae);row('Autorisation generale',data.autorisation_generale);row('Operations similaires',data.operations_similaires);row('Annees experience',data.annees_experience);
 sec('2. Chaine logistique et hubs');row('Chine vers hub',data.china_to_hub);row('Reception au hub',data.receive_hub);row('Navette maritime vers Algerie',data.maritime_to_algeria);row('Livraison site Algerie',data.site_delivery);row('Hub principal',data.primary_hub);row('Hubs disponibles',data.hubs);row('Visa Schengen',data.schengen_visa);row('Autres pays accessibles',data.other_access);row('Demarrage immediat',data.start_immediate);
 sec('3. Capacite d execution et reseau');row('Fourgon',data.van_status);row('Fourgons disponibles',data.vans_now);row('Charge utile moyenne (kg)',data.van_payload_kg);row('Volume utile moyen (m3)',data.van_volume_m3);row('Rotations / mois',data.rotations_month);row('Micro-importateurs maintenant',data.micro_now);row('Micro-importateurs sous 30 jours',data.micro_30);row('Micro-importateurs sous 90 jours',data.micro_90);
 newp();sec('4. Capacite financiere');row('Prefinancement / operation (EUR)',data.finance_operation_eur);row('Capacite mensuelle (EUR)',data.finance_month_eur);row('Delai paiement accepte (jours)',data.payment_delay_days);row('Engagement minimum 18 mois',data.commit_18m);
 sec('5. Grille tarifaire - base exclusive par colis');row('Tarif KG (EUR/kg)',data.rate_kg_eur);row('Tarif UNITE (EUR/colis)',data.rate_unit_eur);row('Tarif M3 (EUR/m3)',data.rate_m3_eur);row('Ferry / fourgon fixe (EUR)',data.fixed_van_ferry_eur);row('Manutention fixe (EUR)',data.handling_fixed_eur);row('Stockage (EUR/jour)',data.storage_eur_day);row('Minimum rotation (EUR)',data.minimum_charge_eur);row('Surcharges / exclusions',data.other_surcharges);
 sec('Regle ELITE de classement');row('Priorite 1','Poids brut P > 5,00 kg = KG, quelle que soit la taille.');row('Priorite 2','Si P <= 5,00 kg et (V > 0,050 m3 ou Dmax > 1,20 m) = M3.');row('Priorite 3','Si P <= 5,00 kg et V <= 0,050 m3 et Dmax <= 1,20 m = UNITE.');row('Acceptation',data.pricing_rule_ack);
 sec('6. Observations et declaration');row('Observations',data.notes);row('Consentement',data.consent);
 const sf=Math.min(100,Math.round(num(data.finance_operation_eur)/200+num(data.finance_month_eur)/1000)),ss=Math.min(100,Math.round(num(data.rotations_month)*8+num(data.micro_90)*3+num(data.vans_now)*5)),se=Math.min(100,Math.round((clean(data.receive_hub)==='OUI'?20:0)+(clean(data.maritime_to_algeria)==='OUI'?20:0)+(clean(data.site_delivery)==='OUI'?20:0)+(clean(data.start_immediate)==='OUI'?20:0)+(clean(data.commit_18m)==='OUI'?20:0)));
 sec('Indicateurs de tri ELITE');row('Indice capacite financiere',`${sf}/100`);row('Indice capacite echelle / reseau',`${ss}/100`);row('Indice execution logistique',`${se}/100`);
 return doc.save()
}
export async function POST(req:Request){try{const data=await req.json() as D;for(const k of required)if(!clean(data[k]))return Response.json({ok:false,error:`Champ requis manquant : ${k}`},{status:400});if(clean(data.pricing_rule_ack)!=='OUI')return Response.json({ok:false,error:'La regle KG / UNITE / M3 doit etre acceptee.'},{status:400});if(clean(data.commit_18m)!=='OUI')return Response.json({ok:false,error:'Le programme exige un engagement de principe sur 18 mois minimum.'},{status:400});const id=ref(),bytes=await pdf(data,id),b64=btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''));return Response.json({ok:true,id,status:'PDF_READY',candidate:`${clean(data.prenom)} ${clean(data.nom)}`,pdf_base64:b64,filename:`ELITE_Candidature_${id}.pdf`})}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:'Erreur serveur'},{status:500})}}
