'use client';
import {FormEvent,useMemo,useState} from 'react';

const steps=['Identité','Chaîne logistique','Capacité','Financement','Tarifs','Validation'];
const yn=<><option value="">Choisir</option><option>OUI</option><option>NON</option></>;
function F({l,n,t='text',r=false,h,s='any',p}:{l:string,n:string,t?:string,r?:boolean,h?:string,s?:string,p?:string}){return <label>{l}{r&&<span className="req"> *</span>}{h&&<span className="hint">{h}</span>}<input name={n} type={t} required={r} step={s} placeholder={p}/></label>}
function Y({l,n,r=false}:{l:string,n:string,r?:boolean}){return <label>{l}{r&&<span className="req"> *</span>}<select name={n} required={r}>{yn}</select></label>}

export default function Home(){
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[sendBusy,setSendBusy]=useState(false),[done,setDone]=useState<any>(null),[form,setForm]=useState<HTMLFormElement|null>(null);
 const progress=useMemo(()=>((step+1)/steps.length)*100,[step]);
 const next=()=>{if(!form)return;const section=form.querySelector(`[data-step="${step}"]`)!;for(const e of [...section.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('[required]')])if(!e.reportValidity())return;setStep(Math.min(step+1,5));window.scrollTo({top:470,behavior:'smooth'})};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;setBusy(true);try{const data=Object.fromEntries(new FormData(e.currentTarget).entries());const rr=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await rr.json();if(!rr.ok||!j.ok)throw new Error(j.error||'Erreur');const bytes=Uint8Array.from(atob(j.pdf_base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));setDone({...j,pdf_url:url,whatsapp_status:'A_ENVOYER'});window.scrollTo({top:0,behavior:'smooth'})}catch(x:any){alert(x.message||'Erreur')}finally{setBusy(false)}};
 const send=async()=>{if(!done||sendBusy||done.whatsapp_status==='ENVOYE')return;setSendBusy(true);try{const rr=await fetch('/api/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:done.id,filename:done.filename,candidate:done.candidate,pdf_base64:done.pdf_base64})});const j=await rr.json();if(rr.ok&&j.ok){setDone({...done,whatsapp_status:'ENVOYE'});return}if(j.code==='CONFIG_REQUIRED'){const bytes=Uint8Array.from(atob(done.pdf_base64),c=>c.charCodeAt(0));const file=new File([bytes],done.filename,{type:'application/pdf'});const nav=navigator as Navigator&{canShare?:(d:ShareData)=>boolean};if(navigator.share&&(!nav.canShare||nav.canShare({files:[file]}))){await navigator.share({files:[file],title:`ELITE - ${done.id}`,text:`ELITE | OFFRE | ${done.id} | WhatsApp +213 770 795 995`});setDone({...done,whatsapp_status:'PARTAGE_OUVERT'});return}throw new Error('Le partage direct de fichier n est pas disponible sur cet appareil. Téléchargez le PDF et joignez-le au WhatsApp +213 770 795 995.')}throw new Error(j.error||'Échec WhatsApp')}catch(x:any){if(x?.name!=='AbortError')alert(x.message||'Erreur WhatsApp')}finally{setSendBusy(false)}};

 if(done)return <main><section className="hero"><div className="brand">ELITE</div><div className="eyebrow">ÉTAPE 1 VALIDÉE · PDF FIGÉ</div><h1>Dossier prêt à transmettre</h1><p>Votre offre est figée dans un PDF individuel. Vérifiez-le puis transmettez uniquement ce document.</p></section><section className="success"><h2>Référence <span className="ref">{done.id}</span></h2><div className={`status ${done.whatsapp_status==='ENVOYE'?'ok':'warn'}`}>{done.whatsapp_status==='ENVOYE'?'Étape 2 terminée : PDF transmis au WhatsApp ELITE +213 770 795 995.':done.whatsapp_status==='PARTAGE_OUVERT'?'Le partage du PDF est ouvert sur votre téléphone. Choisissez WhatsApp puis ELITE +213 770 795 995 et confirmez.':'Étape 2 : appuyez sur le bouton WhatsApp pour transmettre le PDF.'}</div><div className="pdfpreview"><iframe src={done.pdf_url} title="PDF"/></div><div className="actions"><a className="btn secondary" href={done.pdf_url} download={done.filename}>Télécharger le PDF</a><button className="btn whatsapp" onClick={send} disabled={sendBusy||done.whatsapp_status==='ENVOYE'}>{done.whatsapp_status==='ENVOYE'?'✓ PDF envoyé':sendBusy?'Envoi...':'● Envoyer le PDF sur WhatsApp'}</button></div><p className="small">Destinataire : <b>+213 770 795 995</b>. Les réponses détaillées ne sont jamais recopiées comme message texte WhatsApp.</p></section></main>;

 return <main>
 <section className="hero"><div className="brand">ELITE</div><div className="eyebrow">PARTENAIRES LOGISTIQUES · MICRO-IMPORTATION</div><h1>Chine → hub international → navette maritime → Algérie → livraison sur site</h1><p>Programme à volumes importants sur <b>18 mois minimum</b>. Recherche d’opérateurs capables de préfinancer, réceptionner dans un hub relié à l’Algérie, gérer les fourgons et développer un réseau de micro-importateurs.</p><div className="chips"><span className="chip">18 mois minimum</span><span className="chip">Volumes importants</span><span className="chip">Rotations multiples</span><span className="chip">Montée en charge</span></div><div className="hero-actions"><a className="btn primary" href="#formulaire">COMMENCER LE FORMULAIRE</a><a className="btn secondary" href="#regle-tarifaire">Voir la règle KG / M³ / UNITÉ</a></div></section>
 <section className="rule" id="regle-tarifaire"><h2>Fourgon mixte : une seule base de facturation par colis</h2><p className="lead"><b>Unité de décision : le colis de transport de la packing list.</b> P = poids brut, V = L × l × H, Dmax = plus grande dimension. L’ordre ci-dessous est obligatoire.</p><div className="rulegrid"><div className="rulebox"><strong>1 · KG</strong><b>P &gt; 5,00 kg</b><br/>Toujours KG, même volumineux.<br/><span className="formula">kg bruts × EUR/kg</span></div><div className="rulebox"><strong>2 · M³</strong><b>P ≤ 5,00 kg</b> ET (<b>V &gt; 0,050 m³</b> OU <b>Dmax &gt; 1,20 m</b>).<br/><span className="formula">m³ extérieurs × EUR/m³</span></div><div className="rulebox"><strong>3 · UNITÉ</strong><b>P ≤ 5,00 kg</b> ET <b>V ≤ 0,050 m³</b> ET <b>Dmax ≤ 1,20 m</b>.<br/><span className="formula">nombre de colis × EUR/unité</span></div></div><p className="small"><b>Aucun double comptage.</b> Ferry/fourgon, manutention, stockage, attente, transit et autres surcharges sont séparés. Cette grille est une règle contractuelle ELITE de comparaison des offres.</p></section>
 <div className="progress"><div style={{width:`${progress}%`}}/></div>
 <form className="card" id="formulaire" ref={setForm} onSubmit={submit}>
 <section data-step="0" style={{display:step===0?'block':'none'}}><h2>1. Identité et conformité</h2><div className="grid"><F l="Nom" n="nom" r/><F l="Prénom" n="prenom" r/><F l="Téléphone WhatsApp" n="telephone" t="tel" r/><F l="Email" n="email" t="email" r/><F l="Ville / pays d'exploitation" n="ville_pays" r/><F l="Société / réseau / enseigne" n="societe"/><Y l="Carte auto-entrepreneur micro-importation valide ?" n="carte_ae" r/><Y l="Autorisation générale valide ?" n="autorisation_generale" r/><F l="Nombre d'opérations similaires" n="operations_similaires" t="number"/><F l="Années d'expérience" n="annees_experience" t="number" s="0.5"/></div></section>
 <section data-step="1" style={{display:step===1?'block':'none'}}><h2>2. Chaîne Chine → hub → Algérie</h2><div className="grid"><Y l="Peut organiser Chine → hub ?" n="china_to_hub" r/><Y l="Peut réceptionner physiquement au hub ?" n="receive_hub" r/><Y l="Peut organiser la navette maritime vers l'Algérie ?" n="maritime_to_algeria" r/><Y l="Peut livrer sur site ELITE en Algérie ?" n="site_delivery" r/><F l="Hub principal proposé" n="primary_hub" r p="Turquie, Tunisie, Italie..."/><F l="Tous les hubs / pays accessibles" n="hubs" r/><Y l="Visa Schengen disponible ?" n="schengen_visa"/><F l="Autres pays accessibles / titres / réseau" n="other_access"/><Y l="Prêt pour démarrage immédiat ?" n="start_immediate" r/><F l="Sinon, date de disponibilité" n="availability_date" t="date"/></div></section>
 <section data-step="2" style={{display:step===2?'block':'none'}}><h2>3. Fourgons, rotations et réseau</h2><div className="grid"><label>Fourgon disponible *<select name="van_status" required><option value="">Choisir</option><option>PROPRE</option><option>LOUE</option><option>RESEAU</option><option>NON</option></select></label><F l="Fourgons mobilisables maintenant" n="vans_now" t="number"/><F l="Charge utile moyenne / fourgon (kg)" n="van_payload_kg" t="number"/><F l="Volume utile moyen / fourgon (m³)" n="van_volume_m3" t="number" s="0.1"/><F l="Rotations réalistes / mois" n="rotations_month" t="number" s="0.5" r/><F l="Micro-importateurs mobilisables maintenant" n="micro_now" t="number" r/><F l="Micro-importateurs sous 30 jours" n="micro_30" t="number" r/><F l="Micro-importateurs sous 90 jours" n="micro_90" t="number" r/></div></section>
 <section data-step="3" style={{display:step===3?'block':'none'}}><h2>4. Capacité financière</h2><div className="grid"><F l="Préfinancement maximal par opération (EUR)" n="finance_operation_eur" t="number" s="100" r/><F l="Capacité totale mensuelle (EUR)" n="finance_month_eur" t="number" s="100" r/><F l="Délai de paiement maximal accepté après livraison (jours)" n="payment_delay_days" t="number"/><Y l="Engagement sur un programme minimum 18 mois ?" n="commit_18m" r/></div></section>
 <section data-step="4" style={{display:step===4?'block':'none'}}><h2>5. Grille tarifaire</h2><div className="alert ok"><b>KG d’abord, puis M³, sinon UNITÉ.</b> Chaque colis n’a qu’une seule base.</div><div className="grid"><F l="Tarif A — KG (EUR/kg)" n="rate_kg_eur" t="number" s="0.0001" r h="Uniquement colis P > 5,00 kg."/><F l="Tarif B — UNITÉ (EUR/colis)" n="rate_unit_eur" t="number" s="0.0001" r h="P ≤ 5 kg, V ≤ 0,050 m³ et Dmax ≤ 1,20 m."/><F l="Tarif C — M³ (EUR/m³)" n="rate_m3_eur" t="number" s="0.0001" r h="P ≤ 5 kg et (V > 0,050 m³ ou Dmax > 1,20 m)."/><F l="Frais fixe ferry / fourgon (EUR)" n="fixed_van_ferry_eur" t="number" s="0.01"/><F l="Manutention fixe (EUR)" n="handling_fixed_eur" t="number" s="0.01"/><F l="Stockage (EUR/jour)" n="storage_eur_day" t="number" s="0.01"/><F l="Minimum / rotation (EUR)" n="minimum_charge_eur" t="number" s="0.01"/><label className="full">Autres surcharges / exclusions<textarea name="other_surcharges"/></label><Y l="J’accepte la règle exclusive KG / UNITÉ / M³" n="pricing_rule_ack" r/></div></section>
 <section data-step="5" style={{display:step===5?'block':'none'}}><h2>6. Validation du dossier</h2><p className="desc"><b>Étape 1 :</b> validez et générez votre PDF individuel. <b>Étape 2 :</b> vérifiez-le puis appuyez sur WhatsApp pour transmettre uniquement le PDF à ELITE.</p><div className="metrics"><div className="metric"><span>Programme</span><strong>18 mois</strong></div><div className="metric"><span>WhatsApp ELITE</span><strong>+213 770 795 995</strong></div><div className="metric"><span>Format</span><strong>PDF</strong></div><div className="metric"><span>Référence</span><strong>Unique</strong></div></div><label>Observations<textarea name="notes"/></label><label className="check"><input type="checkbox" name="consent" value="OUI" required/><span>Je confirme l’exactitude des informations et j’autorise ELITE à les utiliser pour évaluer cette candidature.</span></label><p className="small">Ce formulaire compare des capacités et offres ; il ne constitue ni une attribution de mission ni une validation réglementaire d’une opération.</p></section>
 <div className="nav"><button type="button" className="btn secondary" disabled={step===0||busy} onClick={()=>setStep(Math.max(0,step-1))}>Retour</button>{step<5?<button type="button" className="btn primary" onClick={next}>Continuer</button>:<button type="submit" className="btn primary" disabled={busy}>{busy?'Génération du PDF...':'VALIDER & GÉNÉRER LE PDF'}</button>}</div>
 </form></main>
}
